name: splash_screen
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/



flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#2C1D57"  # Background color
  image: "images/Betchya login logo.png"

  # Splash screen image should be PNG with transparency
  color_dark: "#2C1D57"  # Background color for dark mode
  image_dark: "images/Betchya login logo.png"  # Optional: separate image for dark mode

  # Full screen mode
  fullscreen: true

  # Android 12 specific settings
  android_12:
    image: "images/Betchya login logo.png"
    icon_background_color: "#2C1D57"
    image_dark: "images/Betchya login logo.png"
    icon_background_color_dark: "#2C1D57"

  # iOS specific settings
  ios_content_mode: center  # Options: center, scaleAspectFit, scaleAspectFill

  # Status bar settings
  android_gravity: center  # Options: center, fill, contain
  ios_gravity: center
  web_image_mode: center

  # Branding settings (optional)
  branding: false
  # branding_mode: bottom  # Uncomment if you want branding

  # Platform specific images (optional)
  # android_screen_orientation: portrait  # Uncomment to force orientation
